# Generated by Django 4.2.13 on 2024-05-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="essay",
            name="essay_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="essay",
            name="related_to_title",
            field=models.BooleanField(default=False),
        ),
    ]
