# Generated by Django 4.2.13 on 2024-05-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essay", "0003_alter_essay_feedback_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_feedback_prompt",
                    models.TextField(
                        default="Please provide feedback on the following essay:\n\n1. Count the number of spelling mistakes and provide the list of misspelled words with their start and end indexes.\n2. Determine if the content of the essay is related to the title (yes/no).\n3. Calculate a quality score for the essay out of 10."
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="essay",
            name="feedback_prompt",
            field=models.TextField(
                default="Please provide feedback on the following essay:\n\n1. Count the number of spelling mistakes and provide the list of misspelled words with their start and end indexes.\n2. Determine if the content of the essay is related to the title (yes/no).\n3. Calculate a quality score for the essay out of 10."
            ),
        ),
    ]
