# Generated by Django 4.2.13 on 2024-05-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essay", "0004_globalsettings_alter_essay_feedback_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essay",
            name="feedback_prompt",
            field=models.TextField(blank=True),
        ),
    ]
